services:
  postgres:
    image: 'postgres:17.5-alpine3.20'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '55432:5432'
